version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      - REDIS_HOST=redis
  migrator:
    build: migrator/
    links:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
